name: "🧪 CI — Compatibility"

on:
  pull_request:
  workflow_dispatch:

jobs:
  node:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        node-version: ["18", "20", "22", "23"]
    name: Node.js ${{ matrix.node-version }}
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: "9.15.0"

      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 👷 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: 🎯 Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-linux-${{ matrix.node-version }}-${{ hashFiles('packages/tusk/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-linux-${{ matrix.node-version }}-
            pnpm-linux-

      - name: 📦 Install Dependencies
        run: |
          cd packages/tusk
          pnpm install
      
      - name: 🧪 Run Tests
        run: |
          cd packages/tusk
          pnpm run test